package com.evora.technologies.saola.data.local.asset

import com.evora.technologies.saola.domain.model.GeoBounds
import com.evora.technologies.saola.domain.model.GeoPoint
import com.evora.technologies.saola.domain.model.Province
import com.evora.technologies.saola.domain.model.ProvinceType
import com.evora.technologies.saola.data.util.log
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * The 34 province outlines, read once from `assets/provinces.json`.
 *
 * The file is generated by `tools/provinces/build_provinces.py` from OpenStreetMap
 * boundaries (ODbL) clipped to a Natural Earth coastline — see that script for why
 * both steps are needed. Shipping it as an asset rather than fetching it keeps the
 * map working offline, which is the only sensible behaviour for something a
 * traveller opens on a mountain with no signal.
 *
 * Coordinates arrive already interleaved as `[lon, lat, …]`, so parsing hands the
 * `DoubleArray` straight through without boxing 9,228 vertices on the way.
 */
internal class ProvinceAssetSource(
    private val assets: BundledAssets,
    private val ioDispatcher: CoroutineDispatcher,
) {

    private val mutex = Mutex()

    // No @Volatile: it is JVM-only, and the mutex below already establishes the
    // happens-before edge that publishing the parsed list needs. The unsynchronised
    // fast read is a benign race — a second reader either sees the finished list or
    // takes the lock and finds it there.
    private var cached: List<Province>? = null

    /** Parsed on first use and held for the process lifetime; the data never changes. */
    suspend fun provinces(): List<Province> {
        cached?.let { return it }
        return mutex.withLock {
            cached ?: load().also { cached = it }
        }
    }

    private suspend fun load(): List<Province> {
        val text = assets.readText(ASSET_NAME) ?: return emptyList()
        return withContext(ioDispatcher) {
            try {
                parseProvinces(text)
            } catch (e: Exception) {
                // A corrupt asset must not take the whole app down: the map shows empty
                // and every other screen carries on working.
                log.e(e) { "Could not parse $ASSET_NAME" }
                emptyList()
            }
        }
    }

    private companion object {
        const val ASSET_NAME = "provinces.json"
    }
}

/**
 * Parses the asset's contents. Split from the IO above so unit tests can run the
 * real 34-province file through the real parser without an Android `Context`.
 */
internal fun parseProvinces(text: String): List<Province> =
    assetJson.decodeFromString(ProvinceFileDto.serializer(), text).provinces.map { it.toDomain() }

private val assetJson = Json { ignoreUnknownKeys = true }

@Serializable
private class ProvinceFileDto(
    val version: Int = 1,
    val source: String = "",
    val provinces: List<ProvinceDto> = emptyList(),
)

@Serializable
private class ProvinceDto(
    val id: String,
    val name: String,
    val nameEn: String = "",
    val type: String = "province",
    val mergedFrom: List<String> = emptyList(),
    /** `[lon, lat]` of a point guaranteed to sit inside the largest ring. */
    val center: DoubleArray = DoubleArray(0),
    /** `[minLon, minLat, maxLon, maxLat]` of the mainland alone. */
    val bbox: DoubleArray = DoubleArray(0),
    /** The same, including the archipelagos. */
    val bboxAll: DoubleArray = DoubleArray(0),
    /** Mainland rings, largest first, each flat `[lon, lat, lon, lat, …]`. */
    val polys: List<DoubleArray> = emptyList(),
    /** Hoàng Sa and Trường Sa, which the map draws in inset boxes. */
    val offshore: List<DoubleArray> = emptyList(),
)

private fun ProvinceDto.toDomain(): Province = Province(
    id = id,
    name = name,
    nameEn = nameEn.ifBlank { name },
    type = if (type == "city") ProvinceType.CITY else ProvinceType.PROVINCE,
    mergedFrom = mergedFrom,
    center = GeoPoint(
        latitude = center.getOrElse(1) { 0.0 },
        longitude = center.getOrElse(0) { 0.0 },
    ),
    // Falls back to the mainland box when `bboxAll` is absent, so an older asset
    // still loads rather than collapsing every province to a zero-size rectangle
    // that rejects every containment test.
    bounds = (bboxAll.takeIf { it.size == 4 } ?: bbox).toBounds(),
    mainlandBounds = bbox.toBounds(),
    mainlandRings = polys.filter { it.size >= 6 },
    offshoreRings = offshore.filter { it.size >= 6 },
)

private fun DoubleArray.toBounds(): GeoBounds = GeoBounds(
    minLongitude = getOrElse(0) { 0.0 },
    minLatitude = getOrElse(1) { 0.0 },
    maxLongitude = getOrElse(2) { 0.0 },
    maxLatitude = getOrElse(3) { 0.0 },
)
