plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.room)
}

// The API keys live in local.properties (git-ignored) so they never reach version control.
// Read through the provider API so they stay compatible with the configuration cache.
fun localProperty(name: String): Provider<String> = providers
    .fileContents(rootProject.layout.projectDirectory.file("local.properties"))
    .asText
    .map { text ->
        text.lineSequence()
            .map(String::trim)
            .firstOrNull { it.startsWith("$name=") }
            ?.substringAfter('=')
            ?.trim()
            .orEmpty()
    }
    .orElse("")

val geminiApiKey: Provider<String> = localProperty("GEMINI_API_KEY")


/*
 * `BuildConfig` is an Android-only construct, and the data layer is no longer
 * Android-only. The one value the code actually reads from it is generated into
 * commonMain instead, so the same source compiles for the JVM and for Kotlin/Native.
 *
 * Note what is *not* here any more: a `DEBUG` constant. This module is built by
 * `com.android.kotlin.multiplatform.library`, which produces a single Android variant
 * — `:app`'s debug and release builds link the very same class file, so a constant
 * generated here cannot tell them apart. It used to be keyed off `-Psaola.debug`,
 * default `true`, which meant a plain `:app:assembleRelease` shipped with Ktor's
 * `Logging` plugin installed. The flag is now passed in at Koin startup by whoever
 * knows the answer: `BuildConfig.DEBUG` on Android, Swift's `#if DEBUG` on iOS.
 * See `networkModule(isDebug)`.
 */
val generateBuildConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildConfig/commonMain/kotlin")
    val apiKey = geminiApiKey

    outputs.dir(outputDir)
    inputs.property("apiKey", apiKey)

    doLast {
        val dir = outputDir.get().asFile
            .resolve("com/evora/technologies/saola/data")
            .apply { mkdirs() }
        dir.resolve("DataBuildConfig.kt").writeText(
            """
            package com.evora.technologies.saola.data

            /**
             * Generated by the `generateBuildConfig` Gradle task — do not edit.
             *
             * Replaces the Android `BuildConfig` the module used before it became
             * multiplatform. Only the one field the code genuinely consumes is
             * emitted, and it is the same for every build type: the key comes from
             * `local.properties`, not from debug-vs-release.
             */
            internal object DataBuildConfig {
                const val GEMINI_API_KEY: String = "${apiKey.get()}"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(17)

    android {
        namespace = "com.evora.technologies.saola.data"
        compileSdk = 37
        minSdk = 26

        // Required for `androidMain/assets/provinces.json` to reach the APK at all: the AGP
        // Kotlin-Multiplatform library plugin leaves the Android asset pipeline disabled unless
        // asked, so without this the file is simply not packaged and province lookup fails at
        // runtime. See the same block in :shared.
        androidResources {
            enable = true
        }

        withHostTest {}
    }

    // iosArm64 for devices, iosSimulatorArm64 for the simulator. iosX64 is deliberately
    // absent: Xcode 26 ships no Intel iOS simulator, and androidx.sqlite:sqlite-bundled
    // — which Room needs on Native — no longer publishes an ios_x64 artifact either.
    iosArm64()
    iosSimulatorArm64()

    // Room's KMP mode requires the same `expect object` constructor on every target,
    // and `Uuid` is still behind an opt-in marker in the 2.3 stdlib.
    compilerOptions {
        optIn.add("kotlin.uuid.ExperimentalUuidApi")
        // Every Objective-C/CoreFoundation binding the Apple actuals touch is behind
        // this marker; annotating each call site would bury the code in opt-ins.
        optIn.add("kotlinx.cinterop.ExperimentalForeignApi")
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuildConfig)

            dependencies {
                api(projects.domain)

                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.io.core)

                // Networking. The engine is per-platform; see androidMain/iosMain.
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.ktor.client.logging)

                // Persistence
                implementation(libs.androidx.room.runtime)
                implementation(libs.androidx.sqlite.bundled)
                // -preferences-core, not -preferences: the latter is the Android-only
                // wrapper that needs a Context to resolve its file.
                implementation(libs.androidx.datastore.preferences.core)
                implementation(libs.okio)

                // DI. Koin replaces Hilt, which is JVM/Android-only by construction.
                implementation(project.dependencies.platform(libs.koin.bom))
                api(libs.koin.core)

                implementation(libs.kermit)
            }
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.turbine)
            implementation(libs.ktor.client.mock)
        }

        // The province-geometry suite reads the shipped asset off disk relative to the
        // project directory, which only works on the JVM — so it stays on JUnit here
        // rather than being forced into commonTest.
        getByName("androidHostTest").dependencies {
            implementation(libs.junit)
        }

        androidMain.dependencies {
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.kotlinx.coroutines.play.services)
            implementation(libs.ktor.client.okhttp)

            implementation(libs.androidx.core.ktx)
            implementation(libs.androidx.exifinterface)
            implementation(libs.play.services.location)
            implementation(libs.koin.android)

            // On-device OCR, one bundled model per script. Bundled rather than
            // downloaded on demand: the traveller is standing in front of a menu,
            // often on a foreign SIM, and a recogniser that has to fetch itself
            // first would fail exactly when it is needed.
            implementation(libs.mlkit.text.recognition.latin)
            implementation(libs.mlkit.text.recognition.chinese)
            implementation(libs.mlkit.text.recognition.japanese)
            implementation(libs.mlkit.text.recognition.korean)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

room {
    schemaDirectory("$projectDir/schemas")
}

dependencies {
    // Room's KSP processor has to run for every target that compiles the @Database,
    // otherwise the generated implementation is missing on that platform.
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
}

/**
 * `provinces.json` has to reach the iOS app bundle too.
 *
 * `src/androidMain/assets` is its canonical home — that is the one location Android packages
 * without any extra wiring — and this task copies it next to the Xcode project, which
 * references the folder rather than individual files. Keeping one copy in version control
 * means the 34 outlines can never drift between platforms.
 *
 * `:shared` is what depends on this, because `:shared` owns the framework Xcode links and its
 * link tasks are the only thing Xcode's build phase invokes.
 *
 * `SharedAssets`, not `Resources`: a directory literally named `Resources` at the root of
 * an iOS `.app` makes CFBundle fall back to the legacy bundle layout and look for
 * `Resources/Info.plist`, so the installer cannot read the bundle identifier at all — the app
 * builds fine and then fails to install with "Missing bundle ID".
 */
val copySharedAssetsToIos by tasks.registering(Sync::class) {
    from(layout.projectDirectory.dir("src/androidMain/assets"))
    into(rootProject.layout.projectDirectory.dir("iosApp/SharedAssets"))
}
