import org.jetbrains.compose.resources.ResourcesExtension

/**
 * Fallback for `vietlens.versionName`, which the root `gradle.properties` declares and `:app`
 * reads for the APK's own version. Only reached if that line is deleted; the point of the
 * property is that the footer on the Settings screen and the APK cannot say different things.
 */
val DEFAULT_VERSION_NAME = "1.0.0"

/**
 * The package the generated `Res` class lives in.
 *
 * Named once because it appears twice: in the `compose.resources` block below, and as a directory
 * inside the iOS bundle layout the resource reader expects.
 */
val RES_PACKAGE = "com.duylt.trave.vietlensai.resources"

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

/*
 * :shared holds the whole presentation layer — every screen, every ViewModel, the
 * navigation graph and the design system — written once against Compose Multiplatform.
 *
 * `:app` is a thin Android host that sets a theme and calls into here, and `iosApp` is
 * an Xcode project that links the framework this module produces. Anything that genuinely
 * differs per platform (the camera, the narration engine, the permission prompts) is an
 * `expect` declaration with an actual in androidMain and iosMain.
 */
/*
 * `BuildConfig` is Android-only, and the Settings screen is not any more. The one field it
 * read — the version name shown in the footer — is generated into commonMain instead.
 */
val generateSharedBuildConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildConfig/commonMain/kotlin")
    val versionName = providers.gradleProperty("vietlens.versionName").orElse(DEFAULT_VERSION_NAME)

    outputs.dir(outputDir)
    inputs.property("versionName", versionName)

    doLast {
        val dir = outputDir.get().asFile
            .resolve("com/duylt/trave/vietlensai")
            .apply { mkdirs() }
        dir.resolve("SharedBuildConfig.kt").writeText(
            """
            package com.duylt.trave.vietlensai

            /** Generated by the `generateSharedBuildConfig` Gradle task — do not edit. */
            internal object SharedBuildConfig {
                const val VERSION_NAME: String = "${versionName.get()}"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(17)

    android {
        namespace = "com.duylt.trave.vietlensai.shared"
        compileSdk = 37
        minSdk = 26

        // Off by default in `com.android.kotlin.multiplatform.library`, unlike the classic
        // `com.android.library` plugin — and with it off the whole Android resource and asset
        // pipeline is skipped for this module. That silently drops the Compose resources:
        // nothing assembles them for the Android target and nothing merges them into the APK,
        // so the app builds and installs and then dies on the first string read with
        // `MissingResourceException: composeResources/…/values/strings.commonMain.cvr`.
        //
        // It is also what registers a generated-assets directory for every Android component,
        // `androidDeviceTest` included. A reflective workaround used to live at the bottom of
        // this file to set that directory by hand, because with the pipeline off AGP never did
        // and Gradle failed task validation; enabling it here is the actual fix, and the
        // workaround has been removed.
        androidResources {
            enable = true
        }

        withHostTest {}

        // The overlay-gesture suite drives a shared composable that is `internal`, so it can
        // only be compiled from inside this module — and it needs a real device to dispatch
        // touch events, which is what a device test is.
        withDeviceTest {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }
    }

    // iosArm64 for devices, iosSimulatorArm64 for the simulator. iosX64 is deliberately
    // absent: Xcode 26 ships no Intel iOS simulator, and androidx.sqlite:sqlite-bundled
    // — which Room needs on Native — no longer publishes an ios_x64 artifact either.
    listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "VietLensShared"
            // Static, not dynamic: a dynamic framework has to be embedded and signed as
            // part of the app bundle, and every Compose symbol would be resolved through
            // dyld at launch. Static links it straight into the executable.
            isStatic = true

            // Re-exported so Swift can name the domain types the shared entry point
            // exposes; without this they are visible to Kotlin but opaque to Xcode.
            export(projects.domain)
        }
    }

    compilerOptions {
        // `LocalClipboard`/`ClipEntry` and the multiplatform `BackHandler` are still marked
        // experimental in Compose Multiplatform 1.12; both are the only APIs for what the
        // translate screen does, so the opt-in is declared once here.
        optIn.add("androidx.compose.ui.ExperimentalComposeUiApi")
        optIn.add("org.jetbrains.compose.resources.ExperimentalResourceApi")
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateSharedBuildConfig)
        }

        commonMain.dependencies {
            api(projects.domain)
            implementation(projects.data)

            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.components.resources)
            // The multiplatform `BackHandler` ships in its own artifact rather than in
            // `compose.ui`, and the plugin has no DSL accessor for it.
            implementation(libs.jetbrains.compose.ui.backhandler)

            // JetBrains' multiplatform ports. Same `androidx.lifecycle` /
            // `androidx.navigation` packages as the Android originals, so the screens
            // and ViewModels needed no import changes.
            implementation(libs.jetbrains.lifecycle.viewmodel)
            implementation(libs.jetbrains.lifecycle.viewmodel.compose)
            implementation(libs.jetbrains.lifecycle.viewmodel.savedstate)
            implementation(libs.jetbrains.lifecycle.runtime.compose)
            implementation(libs.jetbrains.navigation.compose)

            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.koin.compose.viewmodel.navigation)

            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor3)

            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kermit)
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.turbine)
        }

        // The Compose-report gate reads files off disk with `java.io.File`, so it cannot
        // live in commonTest — that source set is also compiled for Kotlin/Native, where
        // there is no such class and no compiler report to read either.
        getByName("androidHostTest").dependencies {
            implementation(kotlin("test"))
        }

        // The overlay-gesture suite drives a shared composable that is `internal`, so it can
        // only be compiled from inside this module — and it needs a real device to dispatch
        // touch events.
        getByName("androidDeviceTest").dependencies {
            implementation(libs.androidx.junit)
            implementation(libs.androidx.compose.ui.test.junit4)
            implementation(libs.androidx.compose.ui.test.manifest)
            implementation(libs.kotlinx.coroutines.test)

            // Named explicitly only to raise them above what `ui-test-junit4` drags in —
            // espresso-core 3.5.0 and runner 1.5.0, which is what made every instrumented
            // test fail on API 37 before its body ran. See the note in `libs.versions.toml`.
            implementation(libs.androidx.test.espresso.core)
            implementation(libs.androidx.test.runner)
        }

        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.core.ktx)
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.koin.android)

            // CameraX drives the viewfinder on Android; iOS uses AVFoundation.
            implementation(libs.androidx.camera.core)
            implementation(libs.androidx.camera.camera2)
            implementation(libs.androidx.camera.lifecycle)
            implementation(libs.androidx.camera.view)

            // The Maps SDK draws the Explore map on Android; iOS uses MapKit, which is
            // already bound by the Kotlin/Native Apple platform libraries and so needs
            // nothing here. The key it reads is declared as `com.google.android.geo.API_KEY`
            // in `:app`'s manifest — a library manifest cannot carry it, because the
            // placeholder is resolved against the *application* being built.
            implementation(libs.maps.compose)
        }
    }
}

compose.resources {
    // A single generated `Res` object for the whole app, public so `:app` can reach the
    // few resources its Android host needs (the window background, mostly).
    publicResClass = true
    packageOfResClass = RES_PACKAGE
    generateResClass = ResourcesExtension.ResourceClassGeneration.Always
}

/*
 * Compose compiler reports, which is what makes recomposition a *testable* property
 * rather than something you notice as jank on a demo phone.
 *
 * For every compilation the plugin writes two files: `…-composables.txt`, which says of
 * each composable whether it is `skippable` and `restartable`, and `…-classes.txt`, which
 * says of each class whether Compose considers it `stable`. A composable that is not
 * skippable re-executes on every recomposition of its parent even when none of its
 * arguments changed; the usual cause is one unstable parameter, and the usual cause of
 * *that* is a class the compiler could not prove immutable.
 *
 * Turned on for every build rather than behind a flag: the reports are a few hundred
 * kilobytes of text and the `composeStabilityCheck` task below reads them, so a build
 * that skipped them would be a build that cannot be verified.
 */
composeCompiler {
    reportsDestination.set(layout.buildDirectory.dir("compose-reports"))
    metricsDestination.set(layout.buildDirectory.dir("compose-reports"))

    // See compose-stability.conf for why the domain layer has to be declared rather
    // than inferred: it is compiled without the Compose plugin, so nothing in it can
    // be proven stable from its bytecode.
    stabilityConfigurationFiles.add(
        layout.projectDirectory.file("compose-stability.conf"),
    )
}

/*
 * `ComposeStabilityReportTest` asserts against the reports the block above produces, so the
 * unit-test task has to know where they are and has to have made sure they exist.
 *
 * The reports are a side effect of compiling rather than a declared task output — the
 * compiler plugin writes them, Gradle does not model them — so they cannot be wired as a
 * task input. The explicit `dependsOn` is what guarantees a report is on disk by the time
 * the test opens it; without it, `test` alone on a clean tree finds nothing and the gate
 * fails for the wrong reason.
 */
tasks.withType<Test>().configureEach {
    dependsOn("compileAndroidMain")
    systemProperty(
        "vietlens.composeReportsDir",
        layout.buildDirectory.dir("compose-reports").get().asFile.absolutePath,
    )
    // `DesignTokenTest` reads the shared sources as text rather than as compiled classes:
    // a hardcoded radius and a `Spacing.lg` compile to the same bytecode, so the only
    // place the difference still exists is the file.
    systemProperty(
        "vietlens.commonMainDir",
        layout.projectDirectory.dir("src/commonMain/kotlin").asFile.absolutePath,
    )
}

/*
 * Compose resources need no wiring of their own.
 *
 * `embedAndSignAppleFrameworkForXcode` — the task Xcode's build phase invokes — pulls in Compose
 * Multiplatform's own `syncComposeResourcesForIos`, which writes straight into
 * `VietLensAI.app/compose-resources`. A hand-rolled copy used to live here, from when the build
 * phase called the raw `link…` task and nothing synced the resources; it is redundant now, and
 * two tasks writing the same tree is how they drift.
 *
 * `provinces.json` is the exception and still needs `:data:copySharedAssetsToIos`: it is a plain
 * asset in `:data`, not a Compose resource, so nothing in the Compose plugin knows about it.
 *
 * One requirement this places on the Xcode project: `ARCHS` must be `arm64` and nothing else.
 * `syncComposeResourcesForIos` maps Xcode's ARCHS to Kotlin targets itself, and for the
 * `iphonesimulator` SDK it recognises only `arm64`/`arm64e` — any other value is
 * `error("Unknown iOS simulator arch: '$arch'")`. Adding an `iosX64()` target would not help,
 * because the plugin has no x86_64 branch to reach it by. So `iosApp.xcodeproj` pins
 * `ARCHS = arm64` in both target configurations, the same as JetBrains' own project template;
 * without it a build for a generic simulator destination gets `arm64 x86_64` and fails here
 * before compiling anything.
 */
tasks.matching { it.name.startsWith("link") && it.name.contains("Ios") }
    .configureEach { dependsOn(":data:copySharedAssetsToIos") }

// The same for the Xcode entry point, which does not go through a `link…` task by that name.
tasks.matching { it.name == "embedAndSignAppleFrameworkForXcode" }
    .configureEach { dependsOn(":data:copySharedAssetsToIos") }
